version: 2
sources:
  - name: raw
    description: Raw data loaded from NYC Open Data
    database: baruch-cis9440-kislam
    schema: nyc_hw3_raw_data 
    tables:
      - name: source_nyc_open_restaurant_apps
        description: |
          NYC 311 service requests for Dept of Transportation.
          One row per service request.
        columns:
          - name: objectid
            description: Unique ID for the service request
            tests:
              - unique
              - not_null
          - name: time_of_submission
            description: Date and time the request was created
          - name: restaurant_name
            description: Full name of the restaurant
          - name: legal_business_name
            description: Full name of the legal business
          - name: doing_business_as
            description: Full name of doing business as
          - name: seating_interest
            description: Type of seating intended
          - name: street
            description: street address of the restaurant
          - name: building_number
            description: building number if any
          - name: postcode
            description: Zip code of the restaurant
          - name: borough
            description: name of borough
          - name: latitude
            description: Latitude coordinate
          - name: longitude
            description: Longitude coordinate
          - name: approved_for_roadway_seating
            description: Dynamically added by Socrata Ingester
          - name: approved_for_sidewalk_seating
            description: Dynamically added by Socrata Ingester
          - name: bbl
            description: Dynamically added by Socrata Ingester
          - name: bin
            description: Dynamically added by Socrata Ingester
          - name: building_number
            description: Dynamically added by Socrata Ingester
          - name: business_address
            description: Dynamically added by Socrata Ingester
          - name: census_tract
            description: Dynamically added by Socrata Ingester
          - name: community_board
            description: Dynamically added by Socrata Ingester
          - name: council_district
            description: Dynamically added by Socrata Ingester
          - name: doing_business_as_dba
            description: Dynamically added by Socrata Ingester
          - name: food_service_establishment
            description: Dynamically added by Socrata Ingester
          - name: globalid
            description: Dynamically added by Socrata Ingester
          - name: healthcompliance_terms
            description: Dynamically added by Socrata Ingester
          - name: landmark_district_or_building
            description: Dynamically added by Socrata Ingester
          - name: landmarkdistrict_terms
            description: Dynamically added by Socrata Ingester
          - name: nta
            description: Dynamically added by Socrata Ingester
          - name: qualify_alcohol
            description: Dynamically added by Socrata Ingester
          - name: roadway_dimensions_area
            description: Dynamically added by Socrata Ingester
          - name: roadway_dimensions_length
            description: Dynamically added by Socrata Ingester
          - name: roadway_dimensions_width
            description: Dynamically added by Socrata Ingester
          - name: seating_interest_sidewalk
            description: Dynamically added by Socrata Ingester
          - name: sidewalk_dimensions_area
            description: Dynamically added by Socrata Ingester
          - name: sidewalk_dimensions_length
            description: Dynamically added by Socrata Ingester
          - name: sidewalk_dimensions_width
            description: Dynamically added by Socrata Ingester
          - name: sla_license_type
            description: Dynamically added by Socrata Ingester
          - name: sla_serial_number
            description: Dynamically added by Socrata Ingester
          - name: zip
            description: Dynamically added by Socrata Ingester


