version: 2
sources:
  - name: raw
    description: Raw data loaded from NYC Open Data
    database: baruch-cis9440-kislam
    schema: nyc_311_raw_data 
    tables:
      - name: source_nyc_open_restaurant_apps
        description: |
          NYC 311 service requests for Dept of Transportation.
          One row per service request.
        columns:
          - name: objectid
            description: Unique ID for the service request
            tests:
              - unique
              - not_null
          - name: time_of_submission
            description: Date and time the request was created
          - name: restaurant_name
            description: Full name of the restaurant
          - name: legal_business_name
            description: Full name of the legal business
          - name: doing_business_as
            description: Full name of doing business as
          - name: seating_interest
            description: Type of seating intended
          - name: street
            description: Street adress of the restaurant
          - name: building_number
            description: building number if any
          - name: postcode
            description: zip code of the restaurant
          - name: borough 
            description: name of borough
          - name: latitude
            description: Latitude coordinate
          - name: longitude
            description: Longitude coordinate
          - name: approved_for_roadway_seating
            description: If approved for roadway seating
          - name: approved_for_sidewalk_seating
            description: If approved for sidewalk seating
          - name: bbl
            description: Borough Block and Lot number (NYC tax lot id)
          - name: bin
            description: bin number if any
          - name: building_number 
            description: Building number if any
          - name: business_address
            description: Business address
          - name: census_tract
            description: Census information
          - name: community_board
            description: NYC Community Board district number
          - name: council_district
            description: Council district
          - name: doing_business_as_dba 
            description: Name of doing business as
          - name: food_service_establishment
            description: Food service establishment
          - name: globalid
            description: Global ID
          - name: healthcompliance_terms
            description: terms of health compliance
          - name: landmark_district_or_building
            description: description of landmark if any
          - name: landmarkdistrict_terms
            description: terms of landmark district
          - name: nta
            description: nta
          - name: qualify_alcohol
            description: if qualifies to sell alcohol
          - name: roadway_dimensions_area
            description: area of roadway dimensions
          - name: roadway_dimension_length
            description: length of roadway
          - name: roadway_dimension_width
            description: width of roadway
          - name: seating_interest_sidewalk
            description: If requesting seating in sidewalk
          - name: sidewalk_dimension_area
            description: Area of sidewalk desired for seating
          - name: sidewalk_dimension_length
            description: length of sidewalk where seating is requested
          - name: sidewalk_dimension_width
            description: width of sidewalk where seating is requested
          - name: sla_license_type
            description: type of licese for sla
          - name: sla_serial_number
            description: number of sla serial
          - name: zip
            description: zip code
